### ISSUE TITLE
3D Bounding Box support

### ISSUE THREAD

**Issue by eduardohenriquearnold** [heremaps/pptk#14]
It would be a nice feature to display 3D bounding boxes within the viewer. 
One could probably add points to obtain the desired effect, but I believe it would be more efficient to have it coded directly in the render interface.

Is this feature a simple one to implement?

**Comment by monghimng** [comment]
Is there any news on this?

**Comment by abhigoku10** [comment]
@hecspc  any updates on this thread ?

**Comment by eduardohenriquearnold** [comment]
It seems that this tool is no longer maintained. If you need features such as 3D bounding boxes I'd recommend using [Mayavi](https://docs.enthought.com/mayavi/mayavi/) or [Open3D](http://www.open3d.org/). The latter has a clear documentation wide community support.
